import { WalletCardData, BoardingPassData, LoyaltyPassData, TicketPassData, AnyPassData } from "@/types/wallet";

export const DEFAULT_3D_BANK_CARDS: WalletCardData[] = [
  {
    id: "card-glass-ultravioleta",
    title: "Nubank Ultravioleta",
    subtitle: "Cartão Premium Glass",
    variant: "glass",
    brand: "mastercard",
    type: "credit",
    balance: 0,
    limit: 25000,
    spent: 4890,
    cardNumber: "•••• •••• •••• 8842",
    holderName: "NOME DO TITULAR",
    expirationDate: "09/31",
    background: "from-[#2A133D]/60 via-[#180B24]/70 to-[#0A0410]/80",
    accentColor: "#A855F7",
    isGlass: true,
    status: "active",
    closingDay: 8,
    dueDay: 15,
  },
  {
    id: "card-titanium-apple",
    title: "Apple Card Titanium",
    subtitle: "Titanium Precision",
    variant: "bank",
    brand: "apple",
    type: "credit",
    balance: 0,
    limit: 50000,
    spent: 7320,
    cardNumber: "•••• •••• •••• 1024",
    holderName: "NOME DO TITULAR",
    expirationDate: "12/30",
    background: "from-[#E5E5EA] via-[#D1D1D6] to-[#C7C7CC]",
    accentColor: "#1D1D1F",
    isGlass: false,
    status: "active",
    closingDay: 12,
    dueDay: 20,
  },
  {
    id: "card-inter-black",
    title: "Inter Black Win",
    subtitle: "Mastercard Black",
    variant: "bank",
    brand: "mastercard",
    type: "credit",
    balance: 0,
    limit: 35000,
    spent: 1250,
    cardNumber: "•••• •••• •••• 4918",
    holderName: "NOME DO TITULAR",
    expirationDate: "04/29",
    background: "from-[#1C1C1E] via-[#141416] to-[#0A0A0C]",
    accentColor: "#F59E0B",
    isGlass: false,
    status: "active",
    closingDay: 5,
    dueDay: 10,
  },
];

export const DEFAULT_PASSES: AnyPassData[] = [
  {
    id: "pass-boarding-latam",
    type: "boarding-pass",
    airline: "LATAM AIRLINES",
    airlineLogoText: "LATAM",
    originCode: "GRU",
    originCity: "São Paulo",
    destinationCode: "JFK",
    destinationCity: "Nova York",
    flightNumber: "LA8180",
    gate: "32B",
    seat: "04A",
    passengerName: "SEU NOME",
    classType: "Executiva • Business",
    boardingTime: "21:15",
    flightDate: "24 OUT 2026",
    terminal: "T3",
    barcodeNumber: "045 8192 3810 4910",
    themeColor: "from-[#0F172A] via-[#1E293B] to-[#0F172A]",
  },
  {
    id: "pass-loyalty-apple",
    type: "loyalty",
    programName: "W Pay Rewards Club",
    category: "Fidelidade & Benefícios",
    pointsBalance: "148.500 pts",
    tier: "Black Member VIP",
    memberId: "WPAY-994821",
    holderName: "SEU NOME",
    validThru: "12/2028",
    barcodeNumber: "9102 4819 0281 7731",
    themeColor: "from-[#1F0A2E] via-[#2A133D] to-[#12051C]",
  },
  {
    id: "pass-ticket-keynote",
    type: "ticket",
    eventName: "Apple Special Keynote 2026",
    venue: "Steve Jobs Theater, Cupertino CA",
    eventDate: "15 NOV 2026",
    eventTime: "10:00 AM PST",
    section: "Keynote VIP",
    row: "A",
    seat: "12",
    attendeeName: "SEU NOME",
    barcodeNumber: "8821 0021 9918 2039",
    themeColor: "from-[#1C1C1E] via-[#242426] to-[#0C0C0E]",
  },
];
